[package]
name = "ornithology"
version = "0.1.0"
edition = "2018"
description = "All your combinatorial needs!"
repository = "https://github.com/pard68/ornithology"
license = "GPL-3.0-only"
authors = ["Ian S. Pringle"]

[dependencies]
masala = "0.2"
